import { v4 as uuidv4 } from "uuid"; 

function chillHop() {
    return [

        {
            name:"Radio Gosen",
            artist: "Christian Radios",
            cover: "https://manuappshome.files.wordpress.com/2022/05/radio-gosen.png",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "https://sp.totalstreaming.net/8125/stream",
            active: true,
        },
        {
            name:"RVE Bucaresti FM 94.2",
            artist: "Christian Radios",
            cover: "https://manuappshome.files.wordpress.com/2022/05/rve-bucaresti-fm-94.2.png",
            id: uuidv4(),
            color: ["#D7B0D5", "#CBDFE0"],
            audio: "https://lb01.bpstream.com:8618/stream/;",
            active: false,
        },
        {
            name:"Radio Filadelfia",
            artist: "Christian Radios",
            cover: "https://manuappshome.files.wordpress.com/2022/05/radio-filadelfia.png",
            id: uuidv4(),
            color: ["#D7B0D5", "#CBDFE0"],
            audio: "http://asculta.radiofiladelfia.ro:8080/stream/2/;",
            active: false,
        },
        {
            name:"Radio Crestin Aripi Spre Cer",
            artist: "Christian Radios",
            cover: "https://manuappshome.files.wordpress.com/2022/05/radio-crestin-aripi-spre-cer.png",
            id: uuidv4(),
            color: ["#1D2731", "#F17E76"],
            audio: "http://radio.stream.aripisprecer.ro/;",
            active: false,
        },
        {
            name:"Vocea Evangheliei FM 88.3",
            artist: "Christian Radios",
            cover: "https://manuappshome.files.wordpress.com/2022/05/vocea-evangheliei-fm-88.3.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://s23.myradiostream.com/:18366/listen.mp3",
            active: false,
        },
        {
            name:"Radio Doxologia",
            artist: "Christian Radios",
            cover: "https://manuappshome.files.wordpress.com/2022/05/radio-doxologia.png",
            id: uuidv4(),
            color: ["#845648","#FDFBDF"],
            audio: "https://rlive.doxologia.ro/stream.mp3",
            active: false,
        },
        {
            name:"Radio Renasterea",
            artist: "Christian Radios",
            cover: "https://manuappshome.files.wordpress.com/2022/05/radio-renasterea.png",
            id: uuidv4(),
            color: ["#578CCE", "#E9D6D0"],
            audio: "https://rlive.radiorenasterea.ro/;stream.mp3?_=1",
            active: false,
        },
        {
            name:"Radio Trinitas",
            artist: "Christian Radios",
            cover: "https://manuappshome.files.wordpress.com/2022/05/radio-trinitas.png",
            id: uuidv4(),
            color: ["#191516", "#82698E"],
            audio: "http://live.radiotrinitas.ro:8003/;",
            active: false,
        },
        {
            name:"Radio Vocea Evangheliei",
            artist: "Christian Radios",
            cover: "https://manuappshome.files.wordpress.com/2022/05/radio-vocea-evangheliei.png",
            id: uuidv4(),
            color: ["#7BC8DD", "#D64A59"],
            audio: "http://94.75.227.133:7280/;audio.mp3",
            active: false,
        },
        {
            name:"Radio VERA Rusia",
            artist: "Christian Radios",
            cover: "https://manuappshome.files.wordpress.com/2019/10/radio-vera-mc3basica-cristiana-clc3a1sica.png",
            id: uuidv4(),
            color: ["#FDE1A9", "#A46874"],
            audio: "http://radiovera.hostingradio.ru:8007/radiovera_128",
            active: false,
        },
        {
            name:"Radio Gospel Hits",
            artist: "Christian Radios",
            cover: "https://manuappshome.files.wordpress.com/2019/10/rc3a1dio-gospel-hits.png",
            id: uuidv4(),
            color: ["#D7B0D5", "#CBDFE0"],
            audio: "http://hts01.kshost.com.br:8836/stream/1/",
            active: false,
        },
        {
            name:"Radio FeLove Instrumentales",
            artist: "Christian Radios",
            cover: "https://manuappshome.files.wordpress.com/2019/10/radio-felove-instrumentales.png",
            id: uuidv4(),
            color: ["#1D2731", "#F17E76"],
            audio: "https://feloveinstrumentales-radiofelove.radioca.st/stream",
            active: false,
        },
        {
            name:"Radio Caprice - Orthodox Spiritual Music",
            artist: "Christian Radios",
            cover: "https://manuappshome.files.wordpress.com/2019/10/radio-caprice-orthodox-spiritual-music-mc3basica-cristiana.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://79.111.14.76:8000/orthodox",
            active: false,
        },
        {
            name:"Radio Vaticana",
            artist: "Christian Radios",
            cover: "https://manuappshome.files.wordpress.com/2019/10/radio-vaticana-italia.png",
            id: uuidv4(),
            color: ["#D7B0D5", "#CBDFE0"],
            audio: "http://live.vaticanwebradio.org/channel5.mp3",
            active: false,
        },
        {
            name:"Ancient Faith Radio - Music",
            artist: "Christian Radios",
            cover: "https://manuappshome.files.wordpress.com/2019/10/ancient-faith-radio.png",
            id: uuidv4(),
            color: ["#1D2731", "#F17E76"],
            audio: "http://ancientfaith.streamguys1.com/music",
            active: false,
        },
        {
            name:"Radio Potencia Mundial Cristiana",
            artist: "Christian Radios",
            cover: "https://manuappshome.files.wordpress.com/2019/10/radio-potencia-mundial-cristiana.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://server.radiogs.net:7024/;",
            active: false,
        },
        {
            name:"Adoration Matinale",
            artist: "Christian Radios",
            cover: "https://manuappshome.files.wordpress.com/2019/10/adoration-matinale-mc3basica-cristiana-gospel.png",
            id: uuidv4(),
            color: ["#D7B0D5", "#CBDFE0"],
            audio: "http://listen.radioking.com/radio/9442/stream/19811",
            active: false,
        },
        {
            name:"Star 93.3 FM",
            artist: "Christian Radios",
            cover: "https://manuappshome.files.wordpress.com/2019/10/n-star-93-3-wakw.png",
            id: uuidv4(),
            color: ["#1D2731", "#F17E76"],
            audio: "https://22213.live.streamtheworld.com/WAKWFMAAC.aac",
            active: false,
        },
        {
            name:"Radio Postreros 93.5 FM",
            artist: "Christian Radios",
            cover: "https://manuappshome.files.wordpress.com/2019/10/atavoz-1.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://108.59.9.147:8170/stream/1/",
            active: false,
        },
        {
            name:"Radio Llamada Final",
            artist: "Christian Radios",
            cover: "https://manuappshome.files.wordpress.com/2021/06/radio-llamada-final-seattle.png",
            id: uuidv4(),
            color: ["#D7B0D5", "#CBDFE0"],
            audio: "https://server.radiogs.org:7049/;",
            active: false,
        },
        {
            name:"Old Fashioned Christian Music",
            artist: "Christian Radios",
            cover: "https://manuappshome.files.wordpress.com/2019/10/old-fashioned-christian-music-radio-mc3basica-cristiana.png",
            id: uuidv4(),
            color: ["#D7B0D5", "#CBDFE0"],
            audio: "http://stream.radio.co/sf2c714555/listen",
            active: false,
        },
        {
            name:"Today's Christian Music 91.1 FM",
            artist: "Christian Radios",
            cover: "https://manuappshome.files.wordpress.com/2019/10/wbgl-todays-christian-music-91-1-fm-mc3basica-cristiana.png",
            id: uuidv4(),
            color: ["#1D2731", "#F17E76"],
            audio: "http://wbgl-ice.streamguys1.com/WBGL-MP3",
            active: false,
        },
         {
            name:"Radio Tygerberg 104FM",
            artist: "Christian Radios",
            cover: "https://manuappshome.files.wordpress.com/2020/11/radio-tygerberg-104fm-en-tunein.png",
            id: uuidv4(),
            color: ["#1D2731", "#F17E76"],
            audio: "http://zas6.ndx.co.za:8007/;",
            active: false,
        },
         {
            name:"Radio Horeb",
            artist: "Christian Radios",
            cover: "https://manuappshome.files.wordpress.com/2019/10/radio-horeb-en-tunein.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://rs16.stream24.org:8000/horeb.mp3",
            active: false,
        },
        {
            name:"Dead To Self Radio",
            artist: "Christian Radios",
            cover: "https://manuappshome.files.wordpress.com/2019/10/dead-to-self-radio.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://puma.streemlion.com:1580/stream",
            active: false,
        },
        {
            name:"Effect Radio Modern Christian",
            artist: "Christian Radios",
            cover: "https://manuappshome.files.wordpress.com/2019/10/effect-radio.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://ice6.securenetsystems.net/EFXAAC",
            active: false,
        },
        {
            name:"Star Auckland New Zealand",
            artist: "Christian Radios",
            cover: "https://manuappshome.files.wordpress.com/2019/10/star-en-tunein.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://rhema-radio.streamguys1.com/rhema-star.aac",
            active: false,
        },
        {
            name:"ACN American Christian Network",
            artist: "Christian Radios",
            cover: "https://manuappshome.files.wordpress.com/2019/10/acn-american-christian-network.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://www.ophanim.net:9720/;",
            active: false,
        },
        {
            name:"Radio Cristiana Josue",
            artist: "Christian Radios",
            cover: "https://manuappshome.files.wordpress.com/2019/10/radio-cristiana-josue-en-tunein.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://enfoquescreativos.com:8010/stream",
            active: false,
        },
        {
            name:"LA X94 - Radio Cristiana",
            artist: "Christian Radios",
            cover: "https://manuappshome.files.wordpress.com/2019/10/la-x94-radio-cristiana.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://securestreams6.autopo.st:2128/stream",
            active: false,
        },
        {
            name:"Radio Voz de la Esperanza",
            artist: "Christian Radios",
            cover: "https://manuappshome.files.wordpress.com/2019/10/radio-voz-de-la-esperanza.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://usa6.fastcast4u.com:5175/stream",
            active: false,
        },
        {
            name:"Inspiracion Radio",
            artist: "Christian Radios",
            cover: "https://manuappshome.files.wordpress.com/2019/10/inspiracic3b3n-radio.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://212.83.135.226:7608/;",
            active: false,
        },
        {
            name:"Ilumina FM 98.1",
            artist: "Christian Radios",
            cover: "https://manuappshome.files.wordpress.com/2019/10/ilumina-fm.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://ss.redradios.net:8026/stream",
            active: false,
        },
        {
            name:"Radio Emanuel Cristiana",
            artist: "Christian Radios",
            cover: "https://manuappshome.files.wordpress.com/2022/05/radio-emanuel-cristiana-1.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://167.114.116.223/8038/stream",
            active: false,
        },
        {
            name:"Radio Estel 106.6 FM",
            artist: "Christian Radios",
            cover: "https://manuappshome.files.wordpress.com/2019/10/rc3a0dio-estel-106-6-fm-mc3basica-cristiana-discusic3b3n.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://srv7021.dns-lcinternet.com:8020/stream",
            active: false,
        },
        {
            name:"Radio Luz Sevilla",
            artist: "Christian Radios",
            cover: "https://manuappshome.files.wordpress.com/2021/06/radio-luz-sevilla.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://radioluzsevilla.ddns.net:8001/;",
            active: false,
        },
        {
            name:"Estereo Emanuel",
            artist: "Christian Radios",
            cover: "https://manuappshome.files.wordpress.com/2019/10/estc3a9reo-emanuel.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://c13.radioboss.fm:18403/stream",
            active: false,
        },
        {
            name:"En Su Presencia",
            artist: "Christian Radios",
            cover: "https://manuappshome.files.wordpress.com/2019/10/generico-cristiano.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://supresenciaradio.out.airtime.pro/supresenciaradio_a",
            active: false,
        },
        {
            name:"Radio Sky FM",
            artist: "Christian Radios",
            cover: "https://manuappshome.files.wordpress.com/2019/10/radio-sky-fm-mc3basica-cristiana.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://stream1.305stream.com/proxy/client217?mp=/stream",
            active: false,
        },
         {
            name:"Shalom Radio Fm",
            artist: "Christian Radios",
            cover: "https://manuappshome.files.wordpress.com/2019/10/generico-cristiano-2.jpg",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://server.radiogs.org:7065/;",
            active: false,
        },
         {
            name:"Adora Radio FM",
            artist: "Christian Radios",
            cover: "https://manuappshome.files.wordpress.com/2019/10/adora-radio-fm.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://stream1.305stream.com:8220/live",
            active: false,
        },
         {
            name:"Nueva Radio Cristiana Salvacion",
            artist: "Christian Radios",
            cover: "https://manuappshome.files.wordpress.com/2019/10/nueva-radio-cristiana-salvacion-emanuel.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://node-10.zeno.fm/5eutpwek2wzuv",
            active: false,
        },
         {
            name:"Radio Life A7D",
            artist: "Christian Radios",
            cover: "https://manuappshome.files.wordpress.com/2019/10/radio-life-a7d.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://node-28.zeno.fm/nsw56m12mceuv",
            active: false,
        },
         {
            name:"Radio Revelacion Cristiana HD",
            artist: "Christian Radios",
            cover: "https://manuappshome.files.wordpress.com/2019/10/radio-revelacic3b3n-cristiana-hd.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://hd.streamingfullhd.net:7051/;",
            active: false,
        },
        {
            name:"Estereo Salvacion",
            artist: "Christian Radios",
            cover: "https://manuappshome.files.wordpress.com/2019/10/estereo-salvacic3b3n.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://server.radiogs.org/8092/stream",
            active: false,
        },
        {
            name:"Radio Cristiana Fm 88.3 Argentina",
            artist: "Christian Radios",
            cover: "https://manuappshome.files.wordpress.com/2019/10/radio-cristiana-mc3basica-cristiana.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://167.114.100.180:5053/;",
            active: false,
        },
        {
            name:"Radio Esperanza 1280 AM",
            artist: "Christian Radios",
            cover: "https://manuappshome.files.wordpress.com/2019/10/wipc-radio-esperanza-1280-am-mc3basica-cristiana.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://s7.viastreaming.net:8925/;stream.nsv/;729071556271275stream.nsv",
            active: false,
        },
        {
            name:"Radio VEA 1570 AM",
            artist: "Christian Radios",
            cover: "https://manuappshome.files.wordpress.com/2019/10/radio-vea.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://ce.redconnections.net:8012/stream",
            active: false,
        },
        {
            name:"Radio Consejero Fiel",
            artist: "Christian Radios",
            cover: "https://manuappshome.files.wordpress.com/2019/10/radio-consejero-fiel.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://node-06.zeno.fm/e7w8u2zvm8quv",
            active: false,
        },
        {
            name:"Alfa y Omega 94.1 FM",
            artist: "Christian Radios",
            cover: "https://manuappshome.files.wordpress.com/2019/10/kbky-radio-alfa-y-omega-94-1-fm-mc3basica-cristiana.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://s6.myradiostream.com:6114/;3438012881573602stream.nsv",
            active: false,
        },
        {
            name:"RADIO LA LUZ Dallas",
            artist: "Christian Radios",
            cover: "https://manuappshome.files.wordpress.com/2019/10/radio-la-luz-mc3basica-cristiana.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://198.178.121.76:8120/stream/1/",
            active: false,
        },
        {
            name:"Dynamis Radio",
            artist: "Christian Radios",
            cover: "https://manuappshome.files.wordpress.com/2019/10/dynamisradio-mc3basica-cristiana.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://control.streaming-pro.com:8014/stream",
            active: false,
        },
        {
            name:"Radio Emanuel",
            artist: "Christian Radios",
            cover: "https://manuappshome.files.wordpress.com/2019/10/radio-emanuel.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://ny.mysonicserver.com/8124/stream",
            active: false,
        },
        {
            name:"Siempre Cristo",
            artist: "Christian Radios",
            cover: "https://manuappshome.files.wordpress.com/2019/10/emisora-siempre-cristo.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://node-22.zeno.fm/fvrx47wpg0quv",
            active: false,
        },
        {
            name:"Radio Dulce Presencia",
            artist: "Christian Radios",
            cover: "https://manuappshome.files.wordpress.com/2019/10/radio-dulce-presencia.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://server.radiogs.net:7139/;",
            active: false,
        },
        {
            name:"Instrumental de Radios Frater",
            artist: "Christian Radios",
            cover: "https://manuappshome.files.wordpress.com/2019/10/instrumental-de-radios-frc3a1ter.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://ce.redconnections.net:8005/stream",
            active: false,
        },
        {
            name:"Cristiana Estereo Restauracion",
            artist: "Christian Radios",
            cover: "https://manuappshome.files.wordpress.com/2019/10/radio-cristiana-estereo-restauracion.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://23.239.68.71:9800/;",
            active: false,
        },
        {
            name:"Filipenses Radio Cristiana",
            artist: "Christian Radios",
            cover: "https://manuappshome.files.wordpress.com/2019/10/filipenses-4-13-radio-cristiana.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://node-20.zeno.fm/7ynu8f0yzbruv",
            active: false,
        },
        {
            name:"Musica Con Vida",
            artist: "Christian Radios",
            cover: "https://manuappshome.files.wordpress.com/2019/10/musica-con-vida.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://streaming.hostingadventista.com:9600/;",
            active: false,
        },
        {
            name:"Radio Eventos Catolicos",
            artist: "Christian Radios",
            cover: "https://manuappshome.files.wordpress.com/2019/10/eventos-catc3b3licos-radio.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://node-03.zeno.fm/1g9cduy10bruv",
            active: false,
        },
        {
            name:"Concertzender Gregoriaans",
            artist: "Christian Radios",
            cover: "https://manuappshome.files.wordpress.com/2019/10/concertzender-gregoriaans-mc3basica-cristiana-clc3a1sica.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://streams.greenhost.nl:8080/gregoriaans",
            active: false,
        },
        {
            name:"Radio Esperance - Chant Gregorien",
            artist: "Christian Radios",
            cover: "https://manuappshome.files.wordpress.com/2019/10/radio-espc3a9rance-chant-grc3a9gorien-mc3basica-cristiana-clc3a1sica.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://esperance.streamakaci.com/gregorien.mp3",
            active: false,
        },
        {
            name:"BBN Spanish",
            artist: "Christian Radios",
            cover: "https://manuappshome.files.wordpress.com/2022/01/christian-radio-app-8-lenguaje-espanol-150.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://audio-edge-5bkfj.fra.h.radiomast.io/475ebed1-595e-4717-b888-64fe8fc6b09f",
            active: false,
        },
        {
            name:"BBN Portugues",
            artist: "Christian Radios",
            cover: "https://manuappshome.files.wordpress.com/2022/01/christian-radio-app-8-lenguaje-portugues-150.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://audio-edge-3mayu.fra.h.radiomast.io/ec065d59-f358-48c9-a288-4efc797e5860",
            active: false,
        },
        {
            name:"BBN English",
            artist: "Christian Radios",
            cover: "https://manuappshome.files.wordpress.com/2022/01/christian-radio-app-8-lenguaje-english-150.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://audio-edge-3mayu.fra.h.radiomast.io/844b0a81-f4b9-485e-adaa-aab8d3ea9f7f",
            active: false,
        },
        {
            name:"BBN German",
            artist: "Christian Radios",
            cover: "https://manuappshome.files.wordpress.com/2022/01/christian-radio-app-8-lenguaje-german-150.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://audio-edge-cmc51.fra.h.radiomast.io/79ce8dd0-c0e9-4443-b887-0fdc1617f8bc",
            active: false,
        },
        {
            name:"BBN Japanese",
            artist: "Christian Radios",
            cover: "https://manuappshome.files.wordpress.com/2022/01/christian-radio-app-8-lenguaje-japones-150.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://audio-edge-cmc51.fra.h.radiomast.io/a622d414-52a6-4426-b3b8-ed2a4dbb704b",
            active: false,
        },
        {
            name:"BBN Chinesse",
            artist: "Christian Radios",
            cover: "https://manuappshome.files.wordpress.com/2022/01/christian-radio-app-8-lenguaje-chinesse-150.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://audio-edge-cmc51.fra.h.radiomast.io/ce298b32-8776-4192-9900-092f44b63e7f",
            active: false,
        },
        {
            name:"BBN Korean",
            artist: "Christian Radios",
            cover: "https://manuappshome.files.wordpress.com/2022/01/christian-radio-app-8-lenguaje-koreano-150.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://audio-edge-5bkfj.fra.h.radiomast.io/678de728-1691-4eb7-bf37-057bcc9b12f5",
            active: false,
        },
         {
            name:"BBN Russian",
            artist: "Christian Radios",
            cover: "https://manuappshome.files.wordpress.com/2022/01/christian-radio-app-8-lenguaje-ruso-150.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://audio-edge-5bkfj.fra.h.radiomast.io/1f7e18dd-42dc-4869-9785-a9800456b9e3",
            active: false,
        },
         {
            name:"BBN Radio Christian Gospel",
            artist: "Christian Radios",
            cover: "https://manuappshome.files.wordpress.com/2022/01/christian-radio-app-8-lenguaje-pulpito-150.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://radiocdn1.streamcomedia.com:5670/tprb1023fm",
            active: false,
        },
        {
            name:"Instrumental Cristiana",
            artist: "Christian Radios",
            cover: "https://manuappshome.files.wordpress.com/2019/10/instrumental-cristiana.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://streams.abidingradio.org:7800/1",
            active: false,
        },
    ];
}

export default chillHop;

