import { v4 as uuidv4 } from "uuid"; 

function chillHop() {
    return [

        {
            name:"Radio Dance EDT - ECIJA",
            artist: "Dance",
            cover: "https://manuappshome.files.wordpress.com/2019/09/radio-dance-edt-electro-c389xitos.png",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "https://secure.tempo-radio.com:1090/;",
            active: true,
        },
        {
            name:"SpaceFM Romania",
            artist: "Dance",
            cover: "https://manuappshome.files.wordpress.com/2022/05/spacefm-romania.png",
            id: uuidv4(),
            color: ["#D7B0D5", "#CBDFE0"],
            audio: "https://spacefm.live/radio/8000/spacefm128",
            active: false,
        },
        {
            name:"Play Radio Hit 90s",
            artist: "Dance",
            cover: "https://manuappshome.files.wordpress.com/2022/05/play-radio-hit-90s.png",
            id: uuidv4(),
            color: ["#D7B0D5", "#CBDFE0"],
            audio: "https://strw1.openstream.co/1421",
            active: false,
        },
        {
            name:"Gherla FM Eurodance",
            artist: "Dance",
            cover: "https://manuappshome.files.wordpress.com/2022/05/gherla-fm-eurodance.png",
            id: uuidv4(),
            color: ["#1D2731", "#F17E76"],
            audio: "http://89.39.189.52:8000/;",
            active: false,
        },
        {
            name:"Radio Club Mix",
            artist: "Dance",
            cover: "https://manuappshome.files.wordpress.com/2022/05/radio-club-mix.jpeg",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://live.radioclubmix.ro:9999/;",
            active: false,
        },
        {
            name:"BN Radio Alemania",
            artist: "Dance",
            cover: "https://manuappshome.files.wordpress.com/2019/09/bn-radio-electro-house.png",
            id: uuidv4(),
            color: ["#845648","#FDFBDF"],
            audio: "https://manuappshome.files.wordpress.com/2019/09/bn-radio-electro-house.png",
            active: false,
        },
        {
            name:"Kiss FM Rumania",
            artist: "Dance",
            cover: "https://manuappshome.files.wordpress.com/2022/05/kiss-fm-rumania.png",
            id: uuidv4(),
            color: ["#578CCE", "#E9D6D0"],
            audio: "https://live.kissfm.ro/kissfm.aacp",
            active: false,
        },
        {
            name:"Trance Resident Paradise",
            artist: "Trance",
            cover: "https://manuappshome.files.wordpress.com/2021/12/trance-resident-paradise-150.png",
            id: uuidv4(),
            color: ["#191516", "#82698E"],
            audio: "http://orion.shoutca.st:8922/stream",
            active: false,
        },
        {
            name:"Eruption Radio UK",
            artist: "Dance",
            cover: "https://manuappshome.files.wordpress.com/2019/10/eruption-radio-uk-en-tunein.png",
            id: uuidv4(),
            color: ["#7BC8DD", "#D64A59"],
            audio: "http://149.255.59.162:8116/stream",
            active: false,
        },
        {
            name:"Funky SX Reino Unido",
            artist: "Funky",
            cover: "https://manuappshome.files.wordpress.com/2019/10/funky-sx-urban-drumnbass.png",
            id: uuidv4(),
            color: ["#FDE1A9", "#A46874"],
            audio: "http://stream1.funkyessex.co.uk:8000/mp3128",
            active: false,
        },
        {
            name:"Loca FM Salamanca",
            artist: "Dance",
            cover: "https://manuappshome.files.wordpress.com/2019/10/loca-fm-salamanca-techno-oldies.png",
            id: uuidv4(),
            color: ["#D7B0D5", "#CBDFE0"],
            audio: "http://s3.we4stream.com:8045/liv",
            active: false,
        },
        {
            name:"krissradio-com",
            artist: "Dance",
            cover: "https://manuappshome.files.wordpress.com/2019/10/krissradio-com.png",
            id: uuidv4(),
            color: ["#1D2731", "#F17E76"],
            audio: "https://ssl.shoutcaststreaming.us:8013/;",
            active: false,
        },
        {
            name:"RT1 IN THE MIX",
            artist: "Dance",
            cover: "https://manuappshome.files.wordpress.com/2019/10/rt1-in-the-mix.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://mp3.hitradiort1.c.nmdn.net/rt1inthemixag/livestream.mp3",
            active: false,
        },
        {
            name:"Dance FM Amsterdam",
            artist: "Dance",
            cover: "https://manuappshome.files.wordpress.com/2019/10/dance-fm-electro-house.png",
            id: uuidv4(),
            color: ["#D7B0D5", "#CBDFE0"],
            audio: "https://streams.dancefm.net/mp3",
            active: false,
        },
        {
            name:"Radio Circuito Mix",
            artist: "Dance",
            cover: "https://manuappshome.files.wordpress.com/2019/09/rc3a1dio-circuito-mix.png",
            id: uuidv4(),
            color: ["#1D2731", "#F17E76"],
            audio: "https://centova01.logicahost.com.br:20003/stream",
            active: false,
        },
        {
            name:"Megastar FM",
            artist: "Dance",
            cover: "https://manuappshome.files.wordpress.com/2019/09/megastarfm-pop-top-40-listas-de-c3a9xitos.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://flucast-b02-01.flumotion.com/cope/megastar.mp3",
            active: false,
        },
        {
            name:"Spectra FM",
            artist: "Dance",
            cover: "https://manuappshome.files.wordpress.com/2019/09/spektra-fm-.png",
            id: uuidv4(),
            color: ["#D7B0D5", "#CBDFE0"],
            audio: "http://stm1.emiteonline.com:8008/spektrafm",
            active: false,
        },
        {
            name:"La Fresca FM",
            artist: "Dance",
            cover: "https://manuappshome.files.wordpress.com/2019/09/la-fresca-fm-top-40-listas-de-c3a9xitos-pop.png",
            id: uuidv4(),
            color: ["#1D2731", "#F17E76"],
            audio: "http://stream.produccionesdale.com:8899/altacalidad",
            active: false,
        },
        {
            name:"Classic Hit 4FM",
            artist: "Dance",
            cover: "https://manuappshome.files.wordpress.com/2019/09/classic-hits-4fm-en-tunein.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://stream.audioxi.com/CLASSIC",
            active: false,
        },
        {
            name:"Radio Top 20 FM - TERRASSA",
            artist: "Dance",
            cover: "https://manuappshome.files.wordpress.com/2019/09/radio-online-e28094-emisoras-de-radio-de-espac3b1a-online-radio-box1.png",
            id: uuidv4(),
            color: ["#D7B0D5", "#CBDFE0"],
            audio: "http://sc1.ipip.cz:8012/;",
            active: false,
        },
        {
            name:"GAY FM Pure Dance",
            artist: "Dance",
            cover: "https://manuappshome.files.wordpress.com/2019/09/gay-fm.png",
            id: uuidv4(),
            color: ["#1D2731", "#F17E76"],
            audio: "http://tuner.gayfm.de/;0337799206539895stream.nsv",
            active: false,
        },
         {
            name:"7 Mix Dance",
            artist: "Dance",
            cover: "https://manuappshome.files.wordpress.com/2019/09/7-de-radio-dance-1.png",
            id: uuidv4(),
            color: ["#1D2731", "#F17E76"],
            audio: "https://edge07.streamonkey.net/radio7-mixshow/stream/mp3",
            active: false,
        },
         {
            name:"Xtreme Mixx Radio",
            artist: "Dance",
            cover: "https://manuappshome.files.wordpress.com/2019/09/xtreme-mixx-radio-.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://87.98.219.178:8156/index.html;stream.nsv",
            active: false,
        },
        {
            name:"MY CLUB",
            artist: "Dance",
            cover: "https://manuappshome.files.wordpress.com/2019/09/myclub.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://myclub.stream.laut.fm/myclub",
            active: false,
        },
        {
            name:"EDM Radio",
            artist: "EDM MUSIC",
            cover: "https://manuappshome.files.wordpress.com/2019/09/edm-radio.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://lk.castnow.ru:8100/edm-320.mp3",
            active: false,
        },
        {
            name:"BigCityBeats FM ",
            artist: "Dance",
            cover: "https://manuappshome.files.wordpress.com/2019/09/bigcitybeats-fm-by-rautemusik-fm-electro-house.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://de-hz-fal-stream06.rautemusik.fm/bigcitybeats",
            active: false,
        },
        {
            name:"Radio Regenbogen - 90er Dance",
            artist: "Dance",
            cover: "https://manuappshome.files.wordpress.com/2019/09/radio-regenbogen-90er-dance-ac3b1os-90.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://streams.regenbogen.de/rr-eurodance-128-mp3?usid=0-0-H-M-D-06",
            active: false,
        },
        {
            name:"Kronehit 90s dance",
            artist: "Dance",
            cover: "https://manuappshome.files.wordpress.com/2019/09/kronehit-90s-dance-ac3b1os-90-1.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://secureonair.krone.at/kronehit21.mp3",
            active: false,
        },
        {
            name:"DnB and EDM - USA",
            artist: "DnB and EDM",
            cover: "https://manuappshome.files.wordpress.com/2021/12/dnbedm-150.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://edmdnb.com:8000/radio.mp3",
            active: false,
        },
        {
            name:"Discover Trance Radio",
            artist: "Trance Music",
            cover: "https://manuappshome.files.wordpress.com/2019/09/discover-trance-radio.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://loki.discovertrance.com/;",
            active: false,
        },
        {
            name:"Q-Dance Amsterdam",
            artist: "Electro-Trance",
            cover: "https://manuappshome.files.wordpress.com/2019/09/q-dance-electro-trance.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://playerservices.streamtheworld.com/api/livestream-redirect/Q_DANCE.mp3",
            active: false,
        },
        {
            name:"ElectroDanceWorld Radio",
            artist: "ElectroDance",
            cover: "https://manuappshome.files.wordpress.com/2019/09/electrodanceworld-radio-trance.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://node-24.zeno.fm/g325adzcrm0uv",
            active: false,
        },
        {
            name:"Trancelovers",
            artist: "Trance Music",
            cover: "https://manuappshome.files.wordpress.com/2019/09/trancelovers.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://stream1.ml0.t4e.dj/trancelovers_high.mp3",
            active: false,
        },
        {
            name:"FM 98.5 Vocal Trance",
            artist: "Trance Music",
            cover: "https://manuappshome.files.wordpress.com/2019/09/fm-98-5-vocal-trance.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://24.168.84.122:8068/;",
            active: false,
        },
        {
            name:"Radio Espace",
            artist: "Dance",
            cover: "https://manuappshome.files.wordpress.com/2019/09/radio-espace-dance-90-en-tunein.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://espace-disco.ice.infomaniak.ch/espace-disco-high.mp3",
            active: false,
        },
        {
            name:"Radio 105 - Dance",
            artist: "Dance",
            cover: "https://manuappshome.files.wordpress.com/2019/09/radio-105-dance-90-ac3b1os-90.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://icy.unitedradio.it/105Dance90.mp3",
            active: false,
        },
        {
            name:"Radio DJ ONE",
            artist: "Dance",
            cover: "https://manuappshome.files.wordpress.com/2022/05/radio-dj-one.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://stream.djradio.ro/radio/8000/stream.mp3",
            active: false,
        },
        {
            name:"Radio DEEA",
            artist: "Dance",
            cover: "https://manuappshome.files.wordpress.com/2022/05/radio-deea.jpeg",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://radiocdn.nxthost.com/radio-deea",
            active: false,
        },
        {
            name:"Eurodance 90",
            artist: "Dance",
            cover: "https://manuappshome.files.wordpress.com/2019/09/eurodance-90-dance-anos-90-house-ac3b1os-90.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://node-08.zeno.fm/g1u270e2ybruv",
            active: false,
        },
         {
            name:"FFH Eurodance",
            artist: "Dance",
            cover: "https://manuappshome.files.wordpress.com/2019/09/ffh-eurodance-ac3b1os-90.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://streams.ffh.de/ffhchannels/mp3/hqeurodance.mp3",
            active: false,
        },
         {
            name:"90 Dance Radio Fm",
            artist: "Dance",
            cover: "https://manuappshome.files.wordpress.com/2019/09/generico-dance.jpg",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://90s90s.hoerradar.de/90s90s-eurodance-mp3-hq",
            active: false,
        },
         {
            name:"One World Radio",
            artist: "Dance",
            cover: "https://manuappshome.files.wordpress.com/2022/05/one-world-radio.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://23623.live.streamtheworld.com/OWR_INTERNATIONAL_ADP_SC",
            active: false,
        },
         {
            name:"Radio Oldies Romania",
            artist: "Dance",
            cover: "https://manuappshome.files.wordpress.com/2022/05/radio-oldies-romania.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://live.radiooldies.ro:9200/stream",
            active: false,
        },
         {
            name:"Radio Party",
            artist: "Dance",
            cover: "https://manuappshome.files.wordpress.com/2022/05/radio-party.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://partyradio.zapto.org:9964/;",
            active: false,
        },
        {
            name:"OneFM",
            artist: "Dance",
            cover: "https://manuappshome.files.wordpress.com/2022/05/onefm.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://live.onefm.ro/onefm.aacp",
            active: false,
        },
        {
            name:"Radio Pro-B",
            artist: "Dance",
            cover: "https://manuappshome.files.wordpress.com/2022/05/radio-pro-b.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://ssl.ascultatare.ro/8888/stream",
            active: false,
        },
        {
            name:"Radio Live247",
            artist: "Dance",
            cover: "https://manuappshome.files.wordpress.com/2022/05/radio-live247.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://stream11.expo-media.eu/radio/8980/;stream.nsv",
            active: false,
        },
        {
            name:"Psychedelik Drum n Bass",
            artist: "Psychedelik",
            cover: "https://manuappshome.files.wordpress.com/2019/10/psychedelik-drumn-bass-en-tunein.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://62.210.114.63:8030/playlist.mp3",
            active: false,
        },
        {
            name:"Radio Record Jungle",
            artist: "Jungle-DrumnBass",
            cover: "https://manuappshome.files.wordpress.com/2019/10/radio-record-jungle-drumnbass.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://hls-01-radiorecord.hostingradio.ru/record-jungle/96/playlist.m3u8",
            active: false,
        },
        {
            name:"Dnb Station",
            artist: "DrumnBass",
            cover: "https://manuappshome.files.wordpress.com/2019/10/dnb-station-en-tunein.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://dnbstation.com:8000/;",
            active: false,
        },
        {
            name:"Jungletrain",
            artist: "Dance",
            cover: "https://manuappshome.files.wordpress.com/2019/10/dosis-decibel-en-jungletrain-net-en-tunein.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://stream5.jungletrain.net:8000/;387436630980872stream.nsv",
            active: false,
        },
        {
            name:"Bassjunkees",
            artist: "DrumnBass",
            cover: "https://manuappshome.files.wordpress.com/2019/10/bassjunkees-drumnbass.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://ducks.and.ponies.listen.bassjunkees.com:8442/;/;7126140696744452stream.nsv",
            active: false,
        },
        {
            name:"BEDLAM DNB",
            artist: "Drum&Bass",
            cover: "https://manuappshome.files.wordpress.com/2019/10/bedlam-dnb-en-tunein.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://c11.radioboss.fm:8318/stream?type=.mp3",
            active: false,
        },
        {
            name:"Break Pirates",
            artist: "Drum&Bass",
            cover: "https://manuappshome.files.wordpress.com/2019/10/break-pirates-electro-drumnbass.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://bpstream.hostco.de:3000/;",
            active: false,
        },
        {
            name:"Dubplate Fm Drum Bass Radio",
            artist: "Drum&Bass",
            cover: "https://manuappshome.files.wordpress.com/2019/10/dubplate-fm-drum-bass-radio-drumnbass.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://sc2.dubplate.fm:5000/DnB/192",
            active: false,
        },
        {
            name:"DirtyBass FM",
            artist: "Drum&Bass",
            cover: "https://manuappshome.files.wordpress.com/2019/10/dirtybass-fm-drumnbass-electro.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://dirtybass.fm:8000/dirtybass_low.mp3",
            active: false,
        },
        {
            name:"Crazy Bass",
            artist: "Drum&Bass",
            cover: "https://manuappshome.files.wordpress.com/2019/10/crazybass-techno-drumnbass.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://crazybass.stream.laut.fm/crazybass",
            active: false,
        },
        {
            name:"Radio Nachtflug",
            artist: "Techno",
            cover: "https://manuappshome.files.wordpress.com/2019/10/radio-nachtflug-gc3b3tico-heavy-metal.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://server26265.streamplus.de/;",
            active: false,
        },
        {
            name:"Drum Base Space",
            artist: "Drum&Bass",
            cover: "https://manuappshome.files.wordpress.com/2019/10/drumbase-space-drumnbass.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://172.105.0.101/radio/8000/radio.mp3",
            active: false,
        },
        {
            name:"Radio Tube Drum Bass",
            artist: "Drum&Bass",
            cover: "https://manuappshome.files.wordpress.com/2019/10/radio-tube-drum-and-bass-drumnbass.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://91.232.4.33:7022/stream/1/",
            active: false,
        },
        {
            name:"UTURN RADIO",
            artist: "Drum&Bass",
            cover: "https://manuappshome.files.wordpress.com/2019/10/uturn-radio-drum-and-bass-drumnbass.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://listen.uturnradio.com/drum_and_bass",
            active: false,
        },
        {
            name:"BassDrive",
            artist: "Drum&Bass",
            cover: "https://manuappshome.files.wordpress.com/2019/10/bassdrive-drumnbass.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://bassdrive.radioca.st:8702/stream/1/",
            active: false,
        },
        {
            name:"DnB Liquified",
            artist: "Drum&Bass",
            cover: "https://manuappshome.files.wordpress.com/2021/12/d-n-b-liquified-160.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://antares.dribbcast.com/proxy/dave1?mp=/stream",
            active: false,
        },
        {
            name:"Future Sounds Radio DNB",
            artist: "Drum&Bass",
            cover: "https://manuappshome.files.wordpress.com/2019/10/radio-dnb-en-tunein.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://streams.radio.co/s03151434c/listen",
            active: false,
        },
        {
            name:"BrokenBeats Atmospheric dnb",
            artist: "Drum&Bass",
            cover: "https://manuappshome.files.wordpress.com/2019/10/brokenbeats-net-atmospheric-dnb-s0urce-en-tunein.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://brokenbeats.net:8000/tune",
            active: false,
        },
        {
            name:"DNB Noize Radio",
            artist: "Drum&Bass",
            cover: "https://manuappshome.files.wordpress.com/2019/10/dnb-noize-radio-en-tunein.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://noizemedia.com:8000/dnbnoize",
            active: false,
        },
        {
            name:"Sky Plus DNB",
            artist: "Drum&Bass",
            cover: "https://manuappshome.files.wordpress.com/2019/10/sky-plus-dnb-en-tunein.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://skymedia-live.bitflip.ee/NRJdnb",
            active: false,
        },
        {
            name:"Dominator Radio",
            artist: "DnB Techno",
            cover: "https://manuappshome.files.wordpress.com/2019/10/dominator-radio.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://gielisgreat.tk:8000/stream",
            active: false,
        },
        {
            name:"Global Beats FM White Channel",
            artist: "EDM Music",
            cover: "https://manuappshome.files.wordpress.com/2019/10/global-dnb-en-tunein.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://gbs01.de:7220/;722330734584306stream.nsv",
            active: false,
        },
         {
            name:"Psychedelik Progressive",
            artist: "Psychedelik",
            cover: "https://manuappshome.files.wordpress.com/2019/10/psychedelic-goa-trance-pro-darkspy.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://62.210.114.63:8010/;",
            active: false,
        },
         {
            name:"BOM Psytrance Radio",
            artist: "Psytrance",
            cover: "https://manuappshome.files.wordpress.com/2019/09/1-fm-bom-psytrance-radio.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://strm112.1.fm/psytrance_mobile_mp3",
            active: false,
        },
         {
            name:"Psyndora Psytrance",
            artist: "Psytrance",
            cover: "https://manuappshome.files.wordpress.com/2019/09/psyndora-psytrance.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://cast.magicstreams.gr:9111/stream",
            active: false,
        },
         {
            name:"Psyradio PsyTrance",
            artist: "Psytrance",
            cover: "https://manuappshome.files.wordpress.com/2019/09/psyradio-psytrance.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://streamer.psyradio.org:8030/;",
            active: false,
        },
         {
            name:"Hirschmilch Psytrance Channel",
            artist: "Psytrance",
            cover: "https://manuappshome.files.wordpress.com/2019/09/hirschmilch-psytrance-channel-electro-trance.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://hirschmilch.de:7000/psytrance.mp3",
            active: false,
        },
         {
            name:"Schizoid PsychedelicTrance",
            artist: "PsyTrance",
            cover: "https://manuappshome.files.wordpress.com/2019/09/radio-schizoid-psychedelic-trance-trance-electro.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://94.130.113.214:8000/schizoid",
            active: false,
        },
         {
            name:"Schizoid Progressive",
            artist: "Progressive",
            cover: "https://manuappshome.files.wordpress.com/2021/12/schizoid_progressive-150.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://94.130.113.214:8000/prog",
            active: false,
        },
         {
            name:"Sunshine live Trance",
            artist: "Trance",
            cover: "https://manuappshome.files.wordpress.com/2019/09/sunshine-live-trance-trance-electro.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://stream.sunshine-live.de/trance/mp3-128/radiode/",
            active: false,
        },
         {
            name:"1Mix Trance",
            artist: "Trance",
            cover: "https://manuappshome.files.wordpress.com/2019/09/1-mix-radio-trance.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://fr3.1mix.co.uk:8000/320",
            active: false,
        },
         {
            name:"GOA Channel ONE",
            artist: "Trance",
            cover: "https://manuappshome.files.wordpress.com/2019/09/goa-channel-one-.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://goa-channel-one.stream.laut.fm/goa-channel-one",
            active: false,
        },
         {
            name:"Toksyna FM Psytrance",
            artist: "Psytrance",
            cover: "https://manuappshome.files.wordpress.com/2019/09/toksyna-fm-psytrance-electro-trance.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://s01.toksyna.fm:8030/stream/1/",
            active: false,
        },
         {
            name:"A State of Trance",
            artist: "Trance",
            cover: "https://manuappshome.files.wordpress.com/2019/09/a-state-of-trance-radio-show.jpg",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://de-hz-fal-stream07.rautemusik.fm/trance",
            active: false,
        },
         {
            name:"Radio Boost",
            artist: "Trance",
            cover: "https://manuappshome.files.wordpress.com/2020/03/radio-boost-en-tunein.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://149.202.22.75:8066/;",
            active: false,
        },
         {
            name:"TranceBase FM",
            artist: "Trance",
            cover: "https://manuappshome.files.wordpress.com/2019/09/trancebase-fm-en-tunein.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://listener1.mp3.tb-group.fm/trb.mp3",
            active: false,
        },
         {
            name:"Absolute Trance Euro Radio",
            artist: "Trance",
            cover: "https://manuappshome.files.wordpress.com/2022/01/absolute-trance-radio.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://strm112.1.fm/trance_mobile_mp3",
            active: false,
        },
         {
            name:"Zone-mix",
            artist: "Trance",
            cover: "https://manuappshome.files.wordpress.com/2019/09/zone-mix.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://zone-mix.stream.laut.fm/zone-mix",
            active: false,
        },
         {
            name:"Puls Trance",
            artist: "Trance",
            cover: "https://manuappshome.files.wordpress.com/2019/09/pulstrance-electro-trance.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://193.200.42.211/pulstranceHD.mp3",
            active: false,
        },
         {
            name:"ETN Trance Toronto",
            artist: "Trance",
            cover: "https://manuappshome.files.wordpress.com/2019/09/etn-trance.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://8.43.48.6:8120/;;",
            active: false,
        },
        {
            name:"Intense Radio",
            artist: "Electro House",
            cover: "https://manuappshome.files.wordpress.com/2019/09/intense-radio-electro-house.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://stream.intenseradio.net:8000/live",
            active: false,
        },
        {
            name:"TrancePulse FM",
            artist: "Trance",
            cover: "https://manuappshome.files.wordpress.com/2019/09/trancepulse-fm-electro-drumnbass.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://stream.trance.ie:8443/stream",
            active: false,
        },
        {
            name:"Radio Caprice Vocal Trance",
            artist: "Trance",
            cover: "https://manuappshome.files.wordpress.com/2022/01/radio-caprice-vocal-trance-150.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://79.120.39.202:8000/vocaltrance",
            active: false,
        },
        {
            name:"1.FM Amsterdam Trance",
            artist: "Trance",
            cover: "https://manuappshome.files.wordpress.com/2022/01/1-fm-amsterdam-trance.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://sc-atr.1.fm:7700/",
            active: false,
        },
        {
            name:"Trance Athena",
            artist: "Trance",
            cover: "https://manuappshome.files.wordpress.com/2019/09/trance-athena.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://cast.streams.ovh:8008/stream",
            active: false,
        },
        {
            name:"Prysm Trance",
            artist: "Trance",
            cover: "https://manuappshome.files.wordpress.com/2019/09/prysm-trance-trance.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://n20a-eu.rcs.revma.com/wnad06xqknruv",
            active: false,
        },
        {
            name:"Digital Impulse",
            artist: "Psy Trance",
            cover: "https://manuappshome.files.wordpress.com/2019/09/digital-impulse-psy-trance.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://orion.shoutca.st:8049/stream",
            active: false,
        },
        {
            name:"FM Trance Buenos Aires",
            artist: "Trance",
            cover: "https://manuappshome.files.wordpress.com/2019/09/fm-trance.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://streaming01.dwservers.net:8100/;",
            active: false,
        },
        {
            name:"Hits for Kids",
            artist: "Kids",
            cover: "https://png.pngtree.com/png-vector/20190726/ourlarge/pngtree-modern-square-cool-music-for-party-lights-png-image_1629696.jpg",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://s1-webradio.antenne.de/hits-fuer-kids/stream/mp3?aw_0_1st.playerid=tunein.com",
            active: false,
        },
        {
            name:"Hits for Kids",
            artist: "Kids",
            cover: "https://png.pngtree.com/png-vector/20190726/ourlarge/pngtree-modern-square-cool-music-for-party-lights-png-image_1629696.jpg",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://s1-webradio.antenne.de/hits-fuer-kids/stream/mp3?aw_0_1st.playerid=tunein.com",
            active: false,
        },
        {
            name:"Hits for Kids",
            artist: "Kids",
            cover: "https://png.pngtree.com/png-vector/20190726/ourlarge/pngtree-modern-square-cool-music-for-party-lights-png-image_1629696.jpg",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://s1-webradio.antenne.de/hits-fuer-kids/stream/mp3?aw_0_1st.playerid=tunein.com",
            active: false,
        },
    ];
}

export default chillHop;

